### ISSUE TITLE
Add title to election card

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/reusable-components#46]
To make it more clear what ballot is selected, we need to add a title to the election card, above the `National` dropdown.

<img width="874" alt="Screenshot 2020-09-22 at 20 48 41" src="https://user-images.githubusercontent.com/15039873/93919906-0cdb5f80-fd17-11ea-82d0-e641f1b80e9f.png">

The title should be formed from the date and the title.

**Comment by dapetcu21** [comment]
Solved in the client repo
