### ISSUE TITLE
Improve code for Referendum handling

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/reusable-components#77]
The code for referendum handling needs to be more robust.
Please checkout these commits:

https://github.com/code4romania/reusable-components/commit/47adc1a02d9ea2697da1b1313f9d8ecbc0209398
https://github.com/code4romania/reusable-components/commit/47adc1a02d9ea2697da1b1313f9d8ecbc0209398

**Comment by dapetcu21** [comment]
I'll take a look at this, but possibly sometime after the weekend.
