### ISSUE TITLE
Correct embed for facebook links

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/reusable-components#87]
When embedding a facebook post, we need to make sure that the embed is correctly displayed in the newsfeed item.

**Comment by dapetcu21** [comment]
So, I researched this a bit and there's no code changes needed. It just needs to be done the right way and Facebook's documentation doesn't make this easy.

Here are the steps:

1. Go to https://developer.facebook.com and make an App ID for Rezultate Vot
2. Go to https://developers.facebook.com/docs/plugins/embedded-posts/ and paste your post's URL in that box
3. Press "Get Code", then Press "IFrame" from the top of the window.
4. Select your App ID.
5. Copy that code and, within it, change two things:
<img width="759" alt="Screenshot 2020-11-10 at 16 01 36" src="https://user-images.githubusercontent.com/428060/98684010-58e96e80-236e-11eb-9faa-a66106923ce0.png">

The first occurence of the width (from the iframe's URL) should be changed to `auto` and the second occurence (from the iframe's width attribute) should be changed to `100%`.

**Comment by RaduCStefanescu** [comment]
@overeha please have a look above, this is what needs to be done on all embeds for facebook links
